In [3]:
import os
import subprocess
import pandas as pd

In [4]:
# https://www.kaggle.com/datasets/shuvomdhar/credit-card-fraud-detection-dataset

In [5]:
def dvc_pull_data(relative_dvc_path:str):
    # Navigate to the root folder of the project
    project_root = os.path.abspath(os.path.join(os.getcwd(),".."))
    # Setup the file path
    file_path = os.path.join(project_root, "data", "fraud_data.csv.dvc")
    # Run the DVC pull command using the full path
    print("DVC pull is complete!")
    return subprocess.run(["dvc", "pull", file_path])

In [6]:
dvc_pull_data("data/fraud_data.csv.dvc")

DVC pull is complete!
Everything is up to date.

CompletedProcess(args=['dvc', 'pull', '/mnt/d/ml_projects/va_mlops/fraud_detection/data/fraud_data.csv.dvc'], returncode=0)

In [9]:
project_root = os.path.abspath(os.path.join(os.getcwd(),".."))
# Setup the file path
file_path = os.path.join(project_root, "data", "fraud_data.csv")

In [10]:
# Load with pandas
df = pd.read_csv(file_path)

In [11]:
df.head()

,step,type,amount,nameOrig,oldbalanceOrg,newbalanceOrig,nameDest,oldbalanceDest,newbalanceDest,isFraud,isFlaggedFraud
0,1,PAYMENT,9839.64,C1231006815,170136.0,160296.36,M1979787155,0.0,0.0,0,0
1,1,PAYMENT,1864.28,C1666544295,21249.0,19384.72,M2044282225,0.0,0.0,0,0
2,1,TRANSFER,181.00,C1305486145,181.0,0.00,C553264065,0.0,0.0,1,0
3,1,CASH_OUT,181.00,C840083671,181.0,0.00,C38997010,21182.0,0.0,1,0
4,1,PAYMENT,11668.14,C2048537720,41554.0,29885.86,M1230701703,0.0,0.0,0,0

In [18]:
df.columns

Index(['step', 'type', 'amount', 'nameOrig', 'oldbalanceOrg', 'newbalanceOrig',
       'nameDest', 'oldbalanceDest', 'newbalanceDest', 'isFraud',
       'isFlaggedFraud'],
      dtype='object')

In [19]:
df.describe()

,step,amount,oldbalanceOrg,newbalanceOrig,oldbalanceDest,newbalanceDest,isFraud,isFlaggedFraud
count,6.362620e+06,6.362620e+06,6.362620e+06,6.362620e+06,6.362620e+06,6.362620e+06,6.362620e+06,6.362620e+06
mean,2.433972e+02,1.798619e+05,8.338831e+05,8.551137e+05,1.100702e+06,1.224996e+06,1.290820e-03,2.514687e-06
std,1.423320e+02,6.038582e+05,2.888243e+06,2.924049e+06,3.399180e+06,3.674129e+06,3.590480e-02,1.585775e-03
min,1.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
25%,1.560000e+02,1.338957e+04,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
50%,2.390000e+02,7.487194e+04,1.420800e+04,0.000000e+00,1.327057e+05,2.146614e+05,0.000000e+00,0.000000e+00
75%,3.350000e+02,2.087215e+05,1.073152e+05,1.442584e+05,9.430367e+05,1.111909e+06,0.000000e+00,0.000000e+00
max,7.430000e+02,9.244552e+07,5.958504e+07,4.958504e+07,3.560159e+08,3.561793e+08,1.000000e+00,1.000000e+00

In [20]:
df.shape

(6362620, 11)