In [10]:
import os
import subprocess
import pandas as pd
from ydata_profiling import ProfileReport

/home/vineet79ankam/miniconda3/envs/mlops-kubeflow/lib/python3.11/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [2]:
# https://www.kaggle.com/datasets/shuvomdhar/credit-card-fraud-detection-dataset

## 1. Load/ Pull the data from DVC

In [3]:
# Define a fucntion to pull the data from DVC
def dvc_pull_data(relative_dvc_path:str):
    # Navigate to the root folder of the project
    project_root = os.path.abspath(os.path.join(os.getcwd(),".."))
    # Setup the file path
    # file_path = os.path.join(project_root, "data", "fraud_data.csv.dvc")
    file_path = os.path.join(project_root, relative_dvc_path)
    # Run the DVC pull command using the full path
    print("DVC pull is complete!")
    return subprocess.run(["dvc", "pull", file_path])

In [4]:
dvc_pull_data("data/fraud_data_v02.csv.dvc")

DVC pull is complete!
Everything is up to date.

CompletedProcess(args=['dvc', 'pull', '/mnt/d/ml_projects/va_mlops/projects/fraud_detection/data/fraud_data_v02.csv.dvc'], returncode=0)

## 2. Read the the csv file as a dataframe

In [5]:
project_root = os.path.abspath(os.path.join(os.getcwd(),".."))
# Setup the file path
file_path = os.path.join(project_root, "data", "fraud_data_v02.csv")

In [6]:
# Load with pandas
df = pd.read_csv(file_path)

In [7]:
df.head()

,Unnamed: 0,trans_date_trans_time,cc_num,merchant,category,amt,first,last,gender,street,...,lat,long,city_pop,job,dob,trans_num,unix_time,merch_lat,merch_long,is_fraud
0,0,2019-01-01 00:00:18,2703186189652095,"fraud_Rippin, Kub and Mann",misc_net,4.97,Jennifer,Banks,F,561 Perry Cove,...,36.0788,-81.1781,3495,"Psychologist, counselling",1988-03-09,0b242abb623afc578575680df30655b9,1325376018,36.011293,-82.048315,0
1,1,2019-01-01 00:00:44,630423337322,"fraud_Heller, Gutmann and Zieme",grocery_pos,107.23,Stephanie,Gill,F,43039 Riley Greens Suite 393,...,48.8878,-118.2105,149,Special educational needs teacher,1978-06-21,1f76529f8574734946361c461b024d99,1325376044,49.159047,-118.186462,0
2,2,2019-01-01 00:00:51,38859492057661,fraud_Lind-Buckridge,entertainment,220.11,Edward,Sanchez,M,594 White Dale Suite 530,...,42.1808,-112.2620,4154,Nature conservation officer,1962-01-19,a1a22d70485983eac12b5b88dad1cf95,1325376051,43.150704,-112.154481,0
3,3,2019-01-01 00:01:16,3534093764340240,"fraud_Kutch, Hermiston and Farrell",gas_transport,45.00,Jeremy,White,M,9443 Cynthia Court Apt. 038,...,46.2306,-112.1138,1939,Patent attorney,1967-01-12,6b849c168bdad6f867558c3793159a81,1325376076,47.034331,-112.561071,0
4,4,2019-01-01 00:03:06,375534208663984,fraud_Keeling-Crist,misc_pos,41.96,Tyler,Garcia,M,408 Bradley Rest,...,38.4207,-79.4629,99,Dance movement psychotherapist,1986-03-28,a41d7549acf90789359a9aa5346dcb46,1325376186,38.674999,-78.632459,0

In [8]:
df.columns

Index(['Unnamed: 0', 'trans_date_trans_time', 'cc_num', 'merchant', 'category',
       'amt', 'first', 'last', 'gender', 'street', 'city', 'state', 'zip',
       'lat', 'long', 'city_pop', 'job', 'dob', 'trans_num', 'unix_time',
       'merch_lat', 'merch_long', 'is_fraud'],
      dtype='object')

In [9]:
df.describe()

,Unnamed: 0,cc_num,amt,zip,lat,long,city_pop,unix_time,merch_lat,merch_long,is_fraud
count,1.296675e+06,1.296675e+06,1.296675e+06,1.296675e+06,1.296675e+06,1.296675e+06,1.296675e+06,1.296675e+06,1.296675e+06,1.296675e+06,1.296675e+06
mean,6.483370e+05,4.171920e+17,7.035104e+01,4.880067e+04,3.853762e+01,-9.022634e+01,8.882444e+04,1.349244e+09,3.853734e+01,-9.022646e+01,5.788652e-03
std,3.743180e+05,1.308806e+18,1.603160e+02,2.689322e+04,5.075808e+00,1.375908e+01,3.019564e+05,1.284128e+07,5.109788e+00,1.377109e+01,7.586269e-02
min,0.000000e+00,6.041621e+10,1.000000e+00,1.257000e+03,2.002710e+01,-1.656723e+02,2.300000e+01,1.325376e+09,1.902779e+01,-1.666712e+02,0.000000e+00
25%,3.241685e+05,1.800429e+14,9.650000e+00,2.623700e+04,3.462050e+01,-9.679800e+01,7.430000e+02,1.338751e+09,3.473357e+01,-9.689728e+01,0.000000e+00
50%,6.483370e+05,3.521417e+15,4.752000e+01,4.817400e+04,3.935430e+01,-8.747690e+01,2.456000e+03,1.349250e+09,3.936568e+01,-8.743839e+01,0.000000e+00
75%,9.725055e+05,4.642255e+15,8.314000e+01,7.204200e+04,4.194040e+01,-8.015800e+01,2.032800e+04,1.359385e+09,4.195716e+01,-8.023680e+01,0.000000e+00
max,1.296674e+06,4.992346e+18,2.894890e+04,9.978300e+04,6.669330e+01,-6.795030e+01,2.906700e+06,1.371817e+09,6.751027e+01,-6.695090e+01,1.000000e+00

In [31]:
df.shape

(1296675, 23)

In [11]:
profile = ProfileReport(df, title="Fraud Data Profiling Report")

In [13]:
profile.to_file("fraud_data_v02_profile_report.html")

Summarize dataset:   0%|                                                          | 0/28 [00:03<?, ?it/s, Describe variable: city_pop]
Summarize dataset:  61%|█████████████████████████████▋                   | 17/28 [00:22<00:17,  1.62s/it, Describe variable: is_fraud]
Summarize dataset:  68%|█████████████████████████████████▎               | 19/28 [00:24<00:13,  1.45s/it, Describe variable: is_fraud]
Summarize dataset:  82%|████████████████████████████████████████▎        | 23/28 [00:28<00:05,  1.09s/it, Describe variable: is_fraud]
100%|█████████████████████████████████████████████████████████████████████████████████████████████████| 23/23 [00:21<00:00,  1.05it/s]
Summarize dataset: 100%|█████████████████████████████████████████████████████████████████| 132/132 [00:54<00:00,  2.40it/s, Completed]
Generate report structure: 100%|████████████████████████████████████████████████████████████████████████| 1/1 [00:04<00:00,  4.83s/it]
Render HTML: 100%|██████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.35s/it]
Export report to file: 100%|████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 19.77it/s]